Added cPlugin:GetLocalFolder
cuberite/CuberitePluginChecker pull request #21
Opened 2016-10-26 08:34 UTC by NiLSPACE

For some reason the `-g` flag was having trouble [here](https://github.com/cuberite/WorldEdit/blob/master/main.lua#L52) otherwise. It probably has something to do with that I use the `cPluginManager:GetCurrentPlugin` method before the `Initialize` function as well.

2016-10-26 09:03 UTC, madmaxoft requested changes

2016-10-26 09:03 UTC, madmaxoft commented on APIImpl/PluginManager.lua
> +		getmetatable(res).__pluginPath = a_Simulator.options.pluginPath
So far the `simulatorInternal_` prefix has been used for all internal simulator variables inside the classes, so it should be used here as well.

2016-10-26 09:03 UTC, madmaxoft commented on APIImpl/PluginManager.lua
> +		return getmetatable(a_Self).__pluginPath
If a `cPlugin` instance was created somewhere else than `cPluginManager:GetCurrentPlugin`, this function will return `nil`. Add `or a_Simulator:createInstance({Type = "string"})`

2016-10-26 09:13 UTC, NiLSPACE commented
Fixed. I'm not sure how the fix the problem where instances of cPlugin's do not have the `simulatorInternal_pluginPath` variable if they are not made in `cPluginManager:GetCurrentPlugin`

2016-10-26 09:46 UTC, madmaxoft commented
You just did the fix. Such plugins will return a random string. At least for now that's okay.

2016-10-26 09:46 UTC, madmaxoft approved these changes

2016-10-26 09:47 UTC, merged

2016-10-26 20:12 UTC, madmaxoft commented
I still wonder why this is necessary, it shouldn't be.

2016-10-26 20:34 UTC, NiLSPACE commented
It only happens with the '-g' flag. Perhaps try it yourself?

2016-10-28 17:45 UTC, madmaxoft commented
Ah, that's because the `-g` flag makes a copy of the parameters before passing them further to the call (so that the params are truly GCed even when they are still held on the stack by the calling functions). Alright then, makes sense.